include:
  - ./url-alias-api/compose.yaml
services:
  api:
    build: ./url-alias-api
    ports:
      - "8080:8080"
    environment:
      SPRING_APPLICATION_JSON: '{
          "spring.profiles.active" : "local"
        }'
    depends_on:
      - db