openapi: 3.0.3
info:
  title: URL Shortener API
  version: 1.0.0
  description: Simple RESTful API for shortening URLs.

paths:
  /shorten:
    post:
      operationId: createNewAlias
      summary: Shorten a URL
      requestBody:
        required: true
        content:
          application/json:
            schema:
              title: newAlias
              type: object
              required:
                - redirectUrl
              properties:
                fullUrl:
                  type: string
                  example: https://example.com/very/long/url
                customAlias:
                  type: string
                  example: my-custom-alias
      responses:
        '201':
          description: URL successfully shortened
          content:
            application/json:
              schema:
                title: createdAlias
                type: object
                properties:
                  shortUrl:
                    type: string
                    example: http://localhost:8080/my-custom-alias
        '400':
          description: Invalid input or alias already taken

  /{alias}:
    get:
      operationId: getRedirectByAlias
      summary: Redirect to full URL
      parameters:
        - name: alias
          in: path
          required: true
          schema:
            type: string
      responses:
        '302':
          description: Redirect to the original URL
        '404':
          description: Alias not found

    delete:
      operationId: deleteAlias
      summary: Delete a shortened URL
      parameters:
        - name: alias
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Successfully deleted
        '404':
          description: Alias not found

  /urls:
    get:
      operationId: getAllUrls
      summary: List all shortened URLs
      responses:
        '200':
          description: A list of shortened URLs
          content:
            application/json:
              schema:
                type: array
                items:
                  title: foundAlias
                  type: object
                  properties:
                    alias:
                      type: string
                      example: my-custom-alias
                    fullUrl:
                      type: string
                      example: https://example.com/very/long/url
                    shortUrl:
                      type: string
                      example: http://localhost:8080/my-custom-alias
