spring:
  data:
    mongodb:
      uri: "mongodb://root:secret@localhost:27017/mydatabase?authSource=admin"
  docker:
    compose:
      enabled: true
      file: ./compose-api-dependencies.yaml
      skip:
        in-tests: false

redirect:
  host: http://localhost
